[site]

name = "Karaty Offical"
title-suffix = " | Karaty Site"
dark-mode = true

[repository]
service = "GitHub"
name = "<github_user>/<github_repo>"

[data-source]
# get more information from document: https://karaty.mrxzx.info/docs/data-source
mode = "<data-source-mode>"
data = "<data-source-config>"

[data-source.local]
# get more information from document: https://karaty.mrxzx.info/docs/data-source
mode = "custom-url"
data = { url = "/data", index-file = "_index.json" }

[navigation]

content = [
    { text = "Home", page = "/" },
    { text = "Docs", link = "https://karaty.mrxzx.info/docs/" },
    { feature = "mode-switch" },
]

[footer]

# enable = false

content = [
    [
        { icon = "brand.github", link = "https://github.com/mrxiaozhuox/karaty" },
        { icon = "solid.table", link = "https://karaty.mrxzx.info/blog/roadmap" },
    ],
    [{ text = "Powered by Karaty" }],
]

[build.static-generator]
source = "data"
target = "data"
